
steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - | 
     echo "***********************"
     echo "$BRANCH_NAME"
     echo "***********************"
- id: 'dag-copy'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "composer/" ]; then
        cd composer
        echo "*************** Copying the DAGs ******************"
        echo "******* At environment: ********"
        echo "*************************************************"
      fi
      bash copy_dags_to_composer.sh ${_DAGS_FOLDER}
      
options:
 logging: CLOUD_LOGGING_ONLY
