steps:
- id: 'data stream'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - | 
     echo "***********************"
     echo "$BRANCH_NAME"
     echo "***********************"
- id: 'datastream-run'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "datastream/" ]; then
        cd datastream
        echo "*************** Stream execution ******************"
        echo "******* At environment: ********"
        echo "*************************************************"
        bash "datastream_setup.sh"
      fi
 
options:
 logging: CLOUD_LOGGING_ONLY
