steps:
- id: 'Table creation'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - | 
     echo "***********************"
     echo "$BRANCH_NAME"
     echo "***********************"
- id: 'ddl-run'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -d "ddl/" ]; then
        cd ddl
        echo "*************** DDL execution ******************"
        echo "******* At environment: ********"
        echo "*************************************************"
        bash "create_tables.sh"
      fi
 
options:
 logging: CLOUD_LOGGING_ONLY
