steps:
- id: 'terraform' 
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - | 
     echo "***********************"
     echo "$BRANCH_NAME"
     echo "***********************"
- id: 'tf init'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ -d "terraform/" ]; then
        cd terraform
        echo "*************** TERRAFORM INIT ******************"
        echo "******* At environment: ********"
        echo "*************************************************"
        terraform init 
      fi
# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ -d "terraform/" ]; then
        cd terraform
        echo "*************************************************"
        echo "*************** TERRAFORM PLAN ******************"
        echo "*************************************************"
        terraform plan 
      fi
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.0.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      if [ -d "terraform" ]; then
        cd terraform
        terraform apply -auto-approve
        echo "*****************Build Status *******************************"
        echo "Branch '$BRANCH_NAME' BUILD COMPLETED SUCCESSFULLY."
        echo "*******************************************************************************"
      fi
# [END tf-apply]      
options:
 logging: CLOUD_LOGGING_ONLY
